

server:
  port: 8085

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/usernagpdemodb
    username: root
    password: ramanjha
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect